### ISSUE TITLE
对于源码阅读的一些困惑.

### ISSUE THREAD

**Issue by Mrwaite** [Ma63d/vue-analysis#8]
我自己的情况是入门前端,会使用vue来构建一些前后端的项目.最近想深入学习vue源码方面的知识,但是介于没有什么源码阅读的经验(jquery等的源码也是阅读甚少), 不知道在入手源码阅读之前应该做怎么样的准备.

是应该先着手简单点的框架源码?还是直接入坑vue?还是先了解一些其他方面的知识,为入坑做准备?

可能问这个问题比较突兀,但是因为最近找实习的刺激吧,想自己往深入的学,而不是只是实用工具.看大佬的博客写的很深入,所以感觉你可以给我一些建议.

最后不管怎么样,都谢谢你.

**Comment by Ma63d** [comment]
您好，其实我也是算是入门前端没多久，从15年大四开始做前端，但是不用怕，直接上。
在读Vue1源码之前我基本是对Vue1的文档和使用非常熟悉了，这比较重要。毕竟源码的功能就是去实现文档上的那些功能、api。如果这一步没做好，你可能不会明白这么做到底是要干嘛。
事先搜了一些vue源码相关的文章，大概的看了一下别人对Vue的理解，这里看得很多。
后来在代码阅读过程中也看了一些尤雨溪本人的采访和沙龙演讲。
然后就开始看源码了，直接硬着头皮上吧。遇到问题就查，一些方法一开始是真的读不懂到底是要干嘛，真的挺苦恼的。但是好在Angular有一些函数名相同的代码，转查Angular反而获得了一些思路。然后基本就是单步调试，多试多思考，结合脑图什么的把概念记录下来，别看了后面，又忘了前面就晕了。然后啃了半个月左右就啃下来了。而且还是过年期间，经常被叫去亲戚打麻将什么的你懂的。。
所以工程量并不大。直接上吧。

另外说点体外的，建议不要在这种系列文章中直接开issue来问问题，可以在具体某篇文章的评论中或者直接发邮件询问我，我git首页有我邮箱。

**Comment by Mrwaite** [comment]
恩,非常感谢你的这些建议,感觉自己应该不会再很迷茫了.

还有就是对于直接开一个issue来问这个问题,是我提问的时候思考的不周到,这里表示很抱歉.

最后还是挺谢谢你愿意花时间解答我这些天的困惑的,很感谢!
