### ISSUE TITLE
冒昧请教一下defineReactive 函数中的 Dep.target 什么时候关联上了 watcher 对象了呢

### ISSUE THREAD

**Issue by tabyouto** [Ma63d/vue-analysis#9]
冒昧请教一下defineReactive 函数中的 Dep.target 什么时候关联上了 watcher 对象了呢

**Comment by Ma63d** [comment]
[watcher 的 beforeGet 方法中](https://github.com/Ma63d/vue-analysis/blob/master/vue%E6%BA%90%E7%A0%81%E6%B3%A8%E9%87%8A%E7%89%88/watcher.js#L197-L199)
有问题请在具体文章底下提问，不要新开 issue，这个项目的 issue 是用来写文章的。
